service: lcme-config-api

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  memorySize: 1024
  timeout: 30

  # Environment variables - you can add more as needed
  environment:
    NODE_ENV: ${opt:stage, 'dev'}
    # Add other environment variables from your .env files here
    # These will replace the env-cmd loading mechanism

  # Define the IAM role permissions
  iamRoleStatements:
    - Effect: Allow
      Action:
        - connect:*
        - logs:*
      Resource: "*"
    # Add any other permissions your Lambda needs

functions:
  api:
    handler: dist/index.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000
